### PR TITLE
Only check the meta rating tag on pages that have one

### LINKED ISSUE #23: A page without a rating throws an exception
Try checking http://yahoo.com

```
rating = page.css("meta[name=rating]")[0]["value"]
```

### PR DESCRIPTION
**Pull request by thomasleese**
Closes #23 .

### CODE REVIEW

File: lib/link_checker/uri_checker/http_checker.rb [hunk 1]
```diff
@@ -76,7 +76,10 @@ def check_get_request
       return unless response
 
       page = Nokogiri::HTML(response.body)
-      rating = page.css("meta[name=rating]")[0]["value"]
+      rating_tag = page.css("meta[name=rating]")
+      return unless rating_tag.try(:any?)
+
+      rating = rating_tag[0]["value"]
```
Comment (kevindew) [inline lib/link_checker/uri_checker/http_checker.rb]: `page.css("meta[name=rating]").first&.fetch("value", nil)`
